version: '3.8'
services:

  application:
    container_name: polymorph
    restart: always
    build: .
    volumes:
     - .:/root
     - ../things:/things
    ports:
     - 4000:4000
    links:
     - database

  notebook:
    container_name: jupyter
    image: jupyter/minimal-notebook:latest
    restart: always
    ports:
     - 8888:8888
    links:
     - database

  database:
    container_name: mongodb
    entrypoint: mongod
    image: mongo:latest
    restart: always
    ports:
     - 27017:27017